<a href="https://colab.research.google.com/github/ubillusg/Utec_programacion_2023/blob/main/modulo_2/3.%20Numpy%20I_revisado_en_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >

<h1 align=center><font size = 5> Numpy - Parte I
</font></h1>

---

## Tabla de Contenidos

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
    
1. <a href="#item31">Trabajando con arrays </a>
2. <a href="#item31">Algebra Matricial con arrays</a>  

</font>
</div>

---

# 1. Trabajando con Arrays

In [ ]:
import numpy as np

In [ ]:
#importando numpy
import numpy as np

In [ ]:
type(np.array([30, 25, 33, 24, 28, 32]))




numpy.ndarray

In [ ]:
np.array(['john', 'marco', 'diego'])

array(['john', 'marco', 'diego'], dtype='<U5')

In [ ]:
np.array([30, 25, 33, 24, 28, 32])

array([30, 25, 33, 24, 28, 32])

In [ ]:
np.array([30, 25, 33, 24, 28, 32],
         [ 8,  3, 10,  1,  5,  9])

TypeError: ignored

In [ ]:
a = np.array([[30, 25, 33, 24, 28, 38],

              [ 8,  3, 10,  1,  5,  9]])


In [ ]:
a

array([list([30, 25, 33, 24, 28]), list([8, 3, 10, 1, 5, 9])],
      dtype=object)

In [ ]:
a = np.array([[[30, 25, 33, 24, 28, 38],
               [ 8,  3, 10,  1,  5,  9],
               [ 5,  6,  5,  7,  5,  4]],
              [[30, 25, 33, 24, 28, 38],
               [ 8,  3, 10,  1,  5,  9],
               [ 5,  6,  5,  7,  5,  4]]])


In [ ]:
a = np.array([[[[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],

               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],

               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],

               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],

               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]]]])



print(a)

[[[[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]]]


In [ ]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

In [ ]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

In [ ]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

### Otras formas de crear arrays

In [ ]:
np.zeros((2, 2))

In [ ]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.full((3, 3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [ ]:

np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange(1, 15 + 1, 3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np.arange(1, 15 + 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# linspace(start, end, n) genera n valores entre el valor start y el valor end
np.linspace(1, 10, 5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.random.random?

In [ ]:
np.random.random((3, 3))

array([[0.06722171, 0.41097194, 0.71345247],
       [0.55150496, 0.13919446, 0.06107904],
       [0.92904352, 0.12965094, 0.51380023]])

In [ ]:
np.random.randint(99)

47

In [ ]:
np.array([np.random.randint(100) for x in range(0,5)])

array([35, 13,  8, 89, 99])

### Atributos de un array

In [ ]:
my_array = np.identity(5)

In [ ]:
my_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Devuelve el número de dimensiones del array
my_array.ndim

2

In [ ]:
a.ndim

4

In [ ]:
5

In [ ]:
#Devuelve una tupla con las dimensiones del array
my_array.shape


(5, 5)

In [ ]:
a.shape

(1, 5, 5, 5)

In [ ]:
a

In [ ]:
#Devuelve el número de elementos del array
my_array.size

25

In [ ]:
a.size

125

In [ ]:
#Devuelve el tipo de datos de los elementos del array
a.dtype

dtype('int64')

In [ ]:
b = np.array(['john', 'jose', 'pablo', 'jose2', 'diegoooooooooooooooooooooooooo'])


In [ ]:
b = np.array(['John', 'Marco'])

In [ ]:
b.dtype

dtype('<U30')

In [ ]:
type(5.0)

float

In [ ]:
type(a)

numpy.ndarray

In [ ]:

b = np.array([1_111_111_111_111_111_111, 'ab'])
b.dtype


dtype('<U21')

### Acceder a elementos del array

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a[1, 0])

4


In [ ]:
# Cuál será la forma de extraer el valor 3 del array

a[0, 2]


3

In [ ]:
# Cuál será la forma de extraer el valor 6 del array
a[1, 2]

6

In [ ]:
a = np.array([[[1, 2, 3], [4, 5, 6], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 99], [4, 5, 6]]])


In [ ]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5, 99],
        [ 4,  5,  6]]])

In [ ]:
a.shape

(2, 3, 3)

In [ ]:
a.ndim

3

In [ ]:
a[1, 1, 2]

99

In [ ]:
a[1][1][2]

99

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1][0])


4


In [ ]:
a[0][2]

3

In [ ]:
print(a[:, 0:2])

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 7, 8]])

a[:, 3:]


array([[4, 5],
       [7, 8]])

In [ ]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 7, 8]])

In [ ]:
a.shape

(2, 5)

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 7, 8], [10, 11, 30, 77, 18]])
a

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  7,  8],
       [10, 11, 30, 77, 18]])

In [ ]:
[[ 3,  7],
 [30, 77]]

In [ ]:
a.shape

(3, 5)

In [ ]:
a[1:, 2:4]


array([[ 3,  7],
       [30, 77]])

### Filtrado de elementos de un array

In [ ]:
import numpy as np

a = np.array([[1, 2, 3, 8], [4, 5, 6, 7]])
res = a[(a > 3) & (a < 8)]

res.reshape(1, 4)


array([[4, 5, 6, 7]])

In [ ]:
a.reshape(4, 2)

array([[1, 2],
       [3, 8],
       [4, 5],
       [6, 7]])

In [ ]:
a[(a > 3)]

array([8, 4, 5, 6, 7])

In [ ]:
a = np.array([[1, 2, 3, 8], [4, 5, 6, 7]])

temp = a[(a%2 == 0)]

temp.reshape(2,2)


array([[2, 8],
       [4, 6]])

In [ ]:
a = a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape


(2, 3)

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[(a % 2 == 0) & (a > 2) & (a < 6)])

[4]


In [ ]:
ciudad_1={'nombre':'Lima',
          'Pais':'Perú',
          'población':'10 MM',
          'Hecho':'Tiene el mejor ceviche y está en el mercado el Eden',
          }
ciudad_2={'nombre':'La Paz',
          'Pais':'Bolivia',
          'población':'1 MM',
          'Hecho':'Tiene la mejor salteña y es la Ortis',
          }
ciudad_3={'nombre':'Santa Cruz',
          'Pais':'Bolivia',
          'población':'3 MM',
          'Hecho':'Tiene el mejor arroz con queso y esta en la casa del Camba',
          }
Ciudades = [ciudad_1,ciudad_2,ciudad_3]

for ciudad in Ciudades:
  print(ciudad.get('nombre'), 'pertenece a', ciudad.get('Pais'), 'tiene una poblacion de', ciudad.get('población'))



Lima pertenece a Perú tiene una poblacion de 10 MM
La Paz pertenece a Bolivia tiene una poblacion de 1 MM
Santa Cruz pertenece a Bolivia tiene una poblacion de 3 MM


In [ ]:
print(a[(a % 2 == 0) &  (a > 2)])

### Operaciones matemáticas con arrays

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b

array([[1, 1, 1],
       [2, 2, 2]])

In [ ]:
print(a + b)

[[2 3 4]
 [6 7 8]]


In [ ]:
print(a / b)

[[1.  2.  3. ]
 [2.  2.5 3. ]]


In [ ]:
print(a ** 2)

[[ 1  4  9]
 [16 25 36]]


# 2. Álgebra matricial con arrays

### Producto escalar de dos vectores

u.dot(v): Devuelve el producto escalar de los vectores u y v.



In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 0, 1])



In [ ]:
a

array([1, 2, 3])

In [ ]:
b

array([1, 0, 1])

In [ ]:
print(a @ b)

4


In [ ]:
print(a.dot(b))

4


In [ ]:
a*b

array([1, 0, 3])

Ejercicio

* a = np.array([[3, 5, 0], [1, 3, 2]])
*b = np.array([[55, 42], [92, 16], [0, 77]])

Multiplique algebraicamente a y b, para esto adapte la matriz b para que se pueda cumplir la multiplicación.

Multiplique de la misma forma pero ahora use un operador aritmético.

In [ ]:
a = np.array([[3, 5, 0], [1, 3, 2]])
b = np.array([[55, 42], [92, 16], [0, 77]])

c = b.reshape(3, 2)
a@c


array([[625, 206],
       [331, 244]])

In [ ]:
c = b.reshape(2, 3)
a*c

array([[165, 210,   0],
       [ 16,   0, 154]])

### Módulo de un vector

norm(v): Devuelve el módulo del vector v.

In [ ]:
a = np.array([3, 4])

In [ ]:
print(np.linalg.norm(a))

5.0


In [ ]:
a = np.array([3, 4, 5])
print(np.linalg.norm(a))


7.0710678118654755


### Producto de dos matrices

a.dot(b) : Devuelve el producto matricial de las matrices a y b siempre y cuando sus dimensiones sean compatibles.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)

[[14 14]
 [32 32]]


In [ ]:
print(a.dot(b))

### Matriz traspuesta

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


### Traza de una matriz

a.trace() : Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(a.trace())

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.trace()

6

### Determinante de una matriz

det(a) : Devuelve el determinante de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

-2.0000000000000004


In [ ]:
1 + 3

4

In [ ]:
0.2 + 0.1

0.30000000000000004

### Matriz inversa

In [ ]:
a = np.array([[1, 2],
              [3, 4]])

print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Autovalores de una matriz


eigvals(a) : Devuelve los autovalores de la matriz cuadrada a.



In [ ]:

a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))


[ 3.00000000e+00  1.00000000e+00 -3.36770206e-17]


### Autovectores de una matriz

eig(a) : Devuelve los autovalores y los autovectores asociados de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eig(a))

(array([ 3.00000000e+00,  1.00000000e+00, -3.36770206e-17]), array([[-4.08248290e-01,  7.07106781e-01,  5.77350269e-01],
       [-8.16496581e-01,  2.61239546e-16, -5.77350269e-01],
       [-4.08248290e-01, -7.07106781e-01,  5.77350269e-01]]))


solve(a, b) : Devuelve la solución del sistema de ecuaciones lineales con los coeficientes de la matriz a y los términos independientes de la matriz b.

In [ ]:
# Sistema de dos ecuaciones y dos incógnitas
# 1*x + 2y = 1
# 3x + 5y = 2

a = np.array([[1, 2],
              [3, 5]])

b = np.array([1,
              2])

print(np.linalg.solve(a, b))


[-1.  1.]


In [ ]:
# Sistema de tres ecuaciones y tres incógnitas
# 10x +  2y -  3z = 1
# 12x +  5y + 17z = 2
#  2x + 50y +  2z = 0

a = np.array([[10, 2, -3],
              [12, 5, 17],
              [2, 50, 2]])

b = np.array([1, 2, 0])

print(np.linalg.solve(a, b))

[ 0.11310345 -0.00610837  0.03960591]


In [ ]:

# 5*x*x + 2*x +3 = 15

# 2*x + 5*z = 12
# 1*z - x**2 = 0





### Solución de un sistema de ecuaciones

---

# Gracias por completar este laboratorio!

---
